// data.jsx — sample products + reference data for BiteLens
// Generic invented brand names to avoid recreating real-brand UI.

const ALLERGEN_LABELS = {
  gluten: 'Gluten', dairy: 'Dairy', eggs: 'Eggs', nuts: 'Tree nuts', peanuts: 'Peanuts',
  soy: 'Soy', fish: 'Fish', shellfish: 'Shellfish', sesame: 'Sesame',
};

const SAMPLE_PRODUCTS = [
  {
    id: 'p_oat_crisps',
    type: 'barcode', favorite: true,
    brand: 'Stoneground',
    name: 'Sea Salt Oat Crisps',
    subtitle: 'Sea Salt · 150g',
    swatch: '#c9a86b', glyph: 'O',
    verdict: 'good', score: 84,
    nutriScore: 'B', ecoScore: 'B', novaGroup: 2,
    summary: 'Whole-grain base, low sugar, no concerning additives.',
    reasons: [
      { kind: 'pos', text: 'Whole-grain oats are the first ingredient' },
      { kind: 'pos', text: 'Low added sugar (1.2g per serving)' },
      { kind: 'pos', text: 'No artificial colors, flavors, or sweeteners' },
      { kind: 'neu', text: 'Moderate sodium — 180mg per serving' },
    ],
    nutrition: { serving: '30g (≈12 crisps)', kcal: 128, protein: 4.2, carbs: 18, sugar: 1.2, fat: 4.1, satFat: 0.6, fiber: 2.8, sodium: 180 },
    ingredients: ['Whole oats', 'Sunflower oil', 'Brown rice flour', 'Sea salt', 'Rosemary extract'],
    allergens: ['gluten'],
    additives: [],
    flags: [],
    timeAgo: 'Just now',
  },
  {
    id: 'p_strawberry_yogurt',
    type: 'barcode',
    brand: 'Meadow Cup',
    name: 'Strawberry Cream Yogurt',
    subtitle: 'Lowfat · 150g cup',
    swatch: '#e8a3a3', glyph: 'Y',
    verdict: 'caution', score: 52,
    nutriScore: 'C', ecoScore: 'C', novaGroup: 4,
    summary: 'Real fruit but heavily sweetened — closer to a dessert.',
    reasons: [
      { kind: 'neg', text: 'High added sugar — 18g per cup (36% DV)' },
      { kind: 'neg', text: 'Contains modified corn starch as a thickener' },
      { kind: 'pos', text: 'Good protein content (6g)' },
      { kind: 'neu', text: 'Includes natural strawberry puree (8%)' },
    ],
    nutrition: { serving: '150g cup', kcal: 142, protein: 6.0, carbs: 22, sugar: 18, fat: 2.4, satFat: 1.5, fiber: 0.4, sodium: 75 },
    ingredients: ['Lowfat milk', 'Sugar', 'Strawberry puree (8%)', 'Modified corn starch', 'Pectin', 'Natural flavor', 'Live cultures'],
    allergens: ['dairy'],
    additives: [
      { code: 'E1442', name: 'Hydroxypropyl distarch phosphate', risk: 'low', detail: 'Modified starch used as a thickener. Generally safe but indicates ultra-processing.' },
      { code: 'E440', name: 'Pectin', risk: 'none', detail: 'Natural fiber from fruit, used as gelling agent. Considered safe.' },
    ],
    flags: [
      { tone: 'caution', label: 'Added sugar', detail: '18g per cup' },
      { tone: 'caution', label: 'Modified starch' },
    ],
    alternatives: ['p_plain_yogurt'],
    timeAgo: '12 min ago',
  },
  {
    id: 'p_cola',
    type: 'barcode',
    brand: 'Crestwave',
    name: 'Citrus Cola Original',
    subtitle: 'Carbonated · 355ml can',
    swatch: '#3a2418', glyph: 'C',
    verdict: 'avoid', score: 17,
    nutriScore: 'E', ecoScore: 'D', novaGroup: 4,
    summary: 'Ultra-processed, nutritionally empty, high sugar load.',
    reasons: [
      { kind: 'neg', text: 'Very high added sugar — 39g per can (78% DV)' },
      { kind: 'neg', text: 'Contains caramel color (Class IV)' },
      { kind: 'neg', text: 'Phosphoric acid — associated with dental erosion' },
      { kind: 'neg', text: 'Zero protein, fiber, or essential nutrients' },
    ],
    nutrition: { serving: '355ml can', kcal: 155, protein: 0, carbs: 39, sugar: 39, fat: 0, satFat: 0, fiber: 0, sodium: 45 },
    ingredients: ['Carbonated water', 'High-fructose corn syrup', 'Caramel color (E150d)', 'Phosphoric acid', 'Natural flavors', 'Caffeine'],
    allergens: [],
    additives: [
      { code: 'E150d', name: 'Caramel color (Class IV)', risk: 'high', detail: 'Sulphite ammonia caramel. Trace 4-MEI is classified by IARC as possibly carcinogenic.' },
      { code: 'E338', name: 'Phosphoric acid', risk: 'moderate', detail: 'Strong acidity associated with enamel erosion and reduced calcium absorption.' },
    ],
    flags: [
      { tone: 'avoid', label: 'High sugar', detail: '39g · 78% DV' },
      { tone: 'avoid', label: 'Caramel color', detail: 'E150d' },
      { tone: 'avoid', label: 'Phosphoric acid' },
      { tone: 'avoid', label: 'Ultra-processed', detail: 'NOVA 4' },
    ],
    alternatives: ['p_sparkling', 'p_kombucha'],
    timeAgo: '1 hr ago',
  },
  {
    id: 'p_grain_bowl',
    type: 'photo',
    brand: '',
    name: 'Grain bowl with salmon',
    subtitle: 'Photo · detected meal',
    swatch: '#7a8a5e', glyph: '◐',
    verdict: 'good', score: 78,
    nutriScore: 'A', ecoScore: 'A', novaGroup: 1,
    summary: 'Balanced plate — lean protein, whole grains, vegetables.',
    confidence: 0.86,
    reasons: [
      { kind: 'pos', text: 'Lean protein (salmon) provides ~24g' },
      { kind: 'pos', text: 'Quinoa and greens deliver fiber + micronutrients' },
      { kind: 'pos', text: 'Visible avocado adds healthy fats' },
      { kind: 'neu', text: 'Dressing not fully visible — calories may vary' },
    ],
    nutrition: { serving: 'Estimated bowl', kcal: 520, protein: 28, carbs: 48, sugar: 6, fat: 22, satFat: 4, fiber: 9, sodium: 480 },
    components: ['Salmon (≈110g)', 'Quinoa', 'Mixed greens', 'Avocado', 'Cherry tomatoes', 'Lemon-tahini dressing'],
    allergens: ['fish', 'sesame'],
    additives: [],
    flags: [],
    timeAgo: '3 hrs ago',
  },
  {
    id: 'p_protein_bar',
    type: 'barcode',
    brand: 'Vertex',
    name: 'Almond Cocoa Protein Bar',
    subtitle: 'Snack · 50g bar',
    swatch: '#5a4030', glyph: 'P',
    verdict: 'caution', score: 58,
    nutriScore: 'C', ecoScore: 'C', novaGroup: 4,
    summary: 'Decent protein, but sweetened with sugar alcohols.',
    reasons: [
      { kind: 'pos', text: '12g protein per bar' },
      { kind: 'neg', text: 'Contains maltitol — may cause digestive issues' },
      { kind: 'neu', text: 'Moderate fiber (5g)' },
    ],
    nutrition: { serving: '50g bar', kcal: 198, protein: 12, carbs: 22, sugar: 5, fat: 9, satFat: 3, fiber: 5, sodium: 140 },
    ingredients: ['Whey protein blend', 'Almonds', 'Maltitol syrup', 'Cocoa', 'Soy lecithin', 'Natural flavor'],
    allergens: ['dairy', 'nuts', 'soy'],
    additives: [
      { code: 'E965', name: 'Maltitol', risk: 'moderate', detail: 'Sugar alcohol. Can cause bloating, gas, or diarrhea in larger amounts.' },
      { code: 'E322', name: 'Soy lecithin', risk: 'low', detail: 'Common emulsifier derived from soy. Generally recognized as safe.' },
    ],
    flags: [{ tone: 'caution', label: 'Maltitol' }],
    timeAgo: 'Yesterday',
  },
  {
    id: 'p_sparkling',
    type: 'barcode', favorite: true,
    brand: 'Rivermark',
    name: 'Cucumber Mint Sparkling',
    subtitle: 'Beverage · 330ml',
    swatch: '#9bbf9b', glyph: 'S',
    verdict: 'good', score: 92,
    nutriScore: 'A', ecoScore: 'A', novaGroup: 1,
    summary: 'Just water and natural flavor. Nothing to worry about.',
    reasons: [
      { kind: 'pos', text: 'Zero sugar, zero sweeteners' },
      { kind: 'pos', text: 'Natural flavors only' },
      { kind: 'pos', text: 'No artificial colors or preservatives' },
    ],
    nutrition: { serving: '330ml can', kcal: 0, protein: 0, carbs: 0, sugar: 0, fat: 0, satFat: 0, fiber: 0, sodium: 15 },
    ingredients: ['Carbonated water', 'Natural cucumber flavor', 'Natural mint flavor'],
    allergens: [],
    additives: [],
    flags: [],
    timeAgo: 'Yesterday',
  },
  {
    id: 'p_plain_yogurt',
    type: 'barcode',
    brand: 'Meadow Cup',
    name: 'Plain Greek Yogurt',
    subtitle: 'Whole milk · 170g cup',
    swatch: '#f5ecd9', glyph: 'G',
    verdict: 'good', score: 88,
    nutriScore: 'A', ecoScore: 'B', novaGroup: 1,
    summary: 'High protein, no added sugar, just two ingredients.',
    reasons: [
      { kind: 'pos', text: 'Excellent protein content (15g)' },
      { kind: 'pos', text: 'No added sugar — only natural lactose' },
      { kind: 'pos', text: 'Live active cultures support gut health' },
    ],
    nutrition: { serving: '170g cup', kcal: 120, protein: 15, carbs: 5, sugar: 5, fat: 5, satFat: 3, fiber: 0, sodium: 50 },
    ingredients: ['Pasteurized whole milk', 'Live active cultures'],
    allergens: ['dairy'],
    additives: [],
    flags: [],
    timeAgo: '2 days ago',
  },
  {
    id: 'p_kombucha',
    type: 'barcode',
    brand: 'Fermentry',
    name: 'Ginger Kombucha',
    subtitle: 'Fermented tea · 330ml',
    swatch: '#c89860', glyph: 'K',
    verdict: 'good', score: 76,
    nutriScore: 'B', ecoScore: 'A', novaGroup: 3,
    summary: 'Low sugar, live cultures, no artificial additives.',
    reasons: [
      { kind: 'pos', text: 'Low sugar (4g per bottle)' },
      { kind: 'pos', text: 'Live probiotic cultures' },
      { kind: 'neu', text: 'Trace alcohol from fermentation (<0.5%)' },
    ],
    nutrition: { serving: '330ml bottle', kcal: 38, protein: 0, carbs: 9, sugar: 4, fat: 0, satFat: 0, fiber: 0, sodium: 10 },
    ingredients: ['Filtered water', 'Black tea', 'Cane sugar', 'Ginger root', 'Live kombucha cultures'],
    allergens: [],
    additives: [],
    flags: [],
    timeAgo: '3 days ago',
  },
];

const PRODUCT_INDEX = Object.fromEntries(SAMPLE_PRODUCTS.map(p => [p.id, p]));

const DEFAULT_PROFILE = {
  diet: 'omnivore',
  allergens: ['nuts'],
  goals: ['low_sugar', 'less_processed'],
};

const DIET_OPTIONS = [
  { id: 'omnivore', label: 'Omnivore' },
  { id: 'vegetarian', label: 'Vegetarian' },
  { id: 'vegan', label: 'Vegan' },
  { id: 'pescatarian', label: 'Pescatarian' },
];

const GOAL_OPTIONS = [
  { id: 'low_sugar', label: 'Low sugar' },
  { id: 'low_sodium', label: 'Low sodium' },
  { id: 'high_protein', label: 'High protein' },
  { id: 'less_processed', label: 'Less processed' },
  { id: 'high_fiber', label: 'High fiber' },
];

Object.assign(window, {
  ALLERGEN_LABELS, SAMPLE_PRODUCTS, PRODUCT_INDEX,
  DEFAULT_PROFILE, DIET_OPTIONS, GOAL_OPTIONS,
});
